apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: media-config
          mountPath: /config
        - name: media-storage
          mountPath: /tv
        - name: sabnzbd-downloads
          mountPath: /downloads
        - name: sabnzbd-incomplete
          mountPath: /incomplete-downloads
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/sonarr
          type: DirectoryOrCreate
      - name: media-storage
        hostPath:
          path: /mnt/sda/data/mediaserver/media/tv
          type: DirectoryOrCreate
      - name: sabnzbd-downloads
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: sabnzbd-incomplete
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett:latest
        ports:
        - containerPort: 9117
        volumeMounts:
        - name: media-config
          mountPath: /config
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config
          type: DirectoryOrCreate
---
apiVersion: apps/v1      
kind: Deployment
metadata:
  name: jellyfin
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: docker.io/jellyfin/jellyfin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8096
          protocol: TCP
        volumeMounts:
        - mountPath: /media
          name: media-storage
          readOnly: false
        - mountPath: /config
          name: jellyfin-config
      restartPolicy: Always
      volumes:
      - name: media-storage
        hostPath:
          path: /mnt/sda/data/mediaserver/media
          type: DirectoryOrCreate
      - name: jellyfin-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/jellyfin
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisparr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisparr
  template:
    metadata:
      labels:
        app: whisparr
    spec:
      containers:
      - name: whisparr
        image: ghcr.io/thespad/whisparr:latest
        ports:
        - containerPort: 8192
        volumeMounts:
        - name: media-config
          mountPath: /config
        - name: sabnzbd-downloads
          mountPath: /downloads
        - name: sabnzbd-incomplete
          mountPath: /incomplete-downloads
        - name: sabnzbd-media
          mountPath: /media
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add: ["NET_BIND_SERVICE"]
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/whisparr
          type: DirectoryOrCreate
      - name: sabnzbd-downloads
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: sabnzbd-incomplete
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: sabnzbd-media
        hostPath:
          path: /mnt/sda/data/mediaserver/media
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: linuxserver/lidarr:latest
        ports:
        - containerPort: 8686
        volumeMounts:
        - name: lidarr-config
          mountPath: /config
        - name: sabnzbd-complete
          mountPath: /downloads
        - name: sabnzbd-incomplete
          mountPath: /incomplete-downloads
        - name: sabnzbd-media
          mountPath: /media
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: sabnzbd-complete
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: sabnzbd-incomplete
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: sabnzbd-media
        hostPath:
          path: /mnt/sda/data/mediaserver/media
          type: DirectoryOrCreate
      - name: lidarr-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/lidarr
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: sabnzbd-config
          mountPath: /config
        - name: sabnzbd-downloads
          mountPath: /downloads
        - name: sabnzbd-incomplete
          mountPath: /incomplete-downloads
        - name: sabnzbd-media
          mountPath: /media
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
      volumes:
      - name: sabnzbd-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/sabnzbd
          type: DirectoryOrCreate
      - name: sabnzbd-downloads
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: sabnzbd-incomplete
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: sabnzbd-media
        hostPath:
          path: /mnt/sda/data/mediaserver/media
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: media-config
          mountPath: /config
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/prowlarr
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: linuxserver/transmission:latest
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: media-config
          mountPath: /config
        - name: media-downloads
          mountPath: /downloads
        - name: media-incomplete
          mountPath: /incomplete-downloads
        - name: transmission-media
          mountPath: /media
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/transmission
          type: DirectoryOrCreate
      - name: media-downloads
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: media-incomplete
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: transmission-media
        hostPath:
          path: /mnt/sda/data/mediaserver/media
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      containers:
      - name: emby
        image: emby/embyserver:latest
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: emby-config
          mountPath: /config
        - name: emby-media
          mountPath: /media
        - name: emby-data
          mountPath: /data
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: emby-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/emby
          type: DirectoryOrCreate
      - name: emby-media
        hostPath:
          path: /mnt/sda/data/mediaserver/media
          type: DirectoryOrCreate
      - name: emby-data
        hostPath:
          path: /mnt/sda/data/mediaserver/data
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: radarr-config
          mountPath: /config
        - name: radarr-media
          mountPath: /movies
        - name: radarr-downloads
          mountPath: /downloads
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: radarr-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/radarr
          type: DirectoryOrCreate
      - name: radarr-media
        hostPath:
          path: /mnt/sda/data/mediaserver/media/movies
          type: DirectoryOrCreate
      - name: radarr-downloads
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
      - name: nzbget
        image: linuxserver/nzbget:latest
        ports:
        - containerPort: 6789
        volumeMounts:
        - name: nzbget-config
          mountPath: /config
        - name: nzbget-downloads
          mountPath: /downloads
        - name: nzbget-incomplete
          mountPath: /incomplete-downloads
        - name: nzbget-media
          mountPath: /media
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: nzbget-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/nzbget
          type: DirectoryOrCreate
      - name: nzbget-downloads
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: nzbget-incomplete
        hostPath:
          path: /mnt/sda/data/mediaserver/download/incomplete
          type: DirectoryOrCreate
      - name: nzbget-media
        hostPath:
          path: /mnt/sda/data/mediaserver/media
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
      - name: bazarr
        image: linuxserver/bazarr:latest
        ports:
        - containerPort: 6767
        volumeMounts:
        - name: bazarr-config
          mountPath: /config
        - name: bazarr-media
          mountPath: /media
        - name: bazarr-downloads
          mountPath: /downloads
        - name: media-storage
          mountPath: /tv
        - name: radarr-media
          mountPath: /movies
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: bazarr-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/bazarr
          type: DirectoryOrCreate
      - name: bazarr-media
        hostPath:
          path: /mnt/sda/data/mediaserver/media
          type: DirectoryOrCreate
      - name: bazarr-downloads
        hostPath:
          path: /mnt/sda/data/mediaserver/download
          type: DirectoryOrCreate
      - name: media-storage
        hostPath:
          path: /mnt/sda/data/mediaserver/media/tv
          type: DirectoryOrCreate
      - name: radarr-media
        hostPath:
          path: /mnt/sda/data/mediaserver/media/movies
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifiarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifiarr
  template:
    metadata:
      labels:
        app: notifiarr
    spec:
      containers:
      - name: notifiarr
        image: ghcr.io/notifiarr/notifiarr:latest
        ports:
        - containerPort: 5454
        volumeMounts:
        - name: notifiarr-config
          mountPath: /config
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: notifiarr-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/notifiarr
          type: DirectoryOrCreate
