apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
      - name: media-volume
        emptyDir: {}
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: media-volume
          mountPath: /mnt/sda/data/mediaserver/config:/sonarr
        - name: media-volume
          mountPath: /mnt/sda/data/mediaserver:/media
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      volumes:
      - name: media-volume
        emptyDir: {}
      containers:
      - name: jackett
        image: linuxserver/jackett:latest
        ports:
        - containerPort: 9117
        volumeMounts:
        - name: media-volume
          mountPath: /mnt/sda/data/mediaserver/config:/jackett

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: docker.io/jellyfin/jellyfin
        imagePullPolicy: IfNotPresent
        name: jellyfin
        ports:
        - containerPort: 8096
          protocol: TCP
        volumeMounts:
        - mountPath: /data/media
          name: media
          readOnly: True
        - mountPath: /config
          name: jellyfin-config
      restartPolicy: Always
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisparr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisparr
  template:
    metadata:
      labels:
        app: whisparr
    spec:
      volumes:
      - name: media-volume
        emptyDir: {}
      containers:
      - name: whisparr
        image: linuxserver/whisparr:latest
        ports:
        - containerPort: 8192
        volumeMounts:
        - name: media-volume
          mountPath: /mnt/sda/data/mediaserver/config:/whisparr
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      volumes:
      - name: media-volume
        emptyDir: {}
      containers:
      - name: lidarr
        image: linuxserver/lidarr:latest
        ports:
        - containerPort: 8686
        volumeMounts:
        - name: media-volume
          mountPath: /mnt/sda/data/mediaserver/config:/lidarr
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      volumes:
      - name: media-volume
        emptyDir: {}
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: media-volume
          mountPath: /mnt/sda/data/mediaserver/config:/prowlarr
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
