apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: emby-config
          mountPath: /config
          subPath: mediaserver/config/sonarr
        - name: emby-config
          mountPath: /tv
          subPath: mediaserver/media/tv
        - name: emby-config
          mountPath: /animation
          subPath: mediaserver/media/animation
        - name: emby-config
          mountPath: /downloads
          subPath: mediaserver/download
        - name: emby-config
          mountPath: /incomplete-downloads
          subPath: mediaserver/download
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: emby-config
        nfs:
          path: /data
          server: 192.168.1.190

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: linuxserver/lidarr:latest
        ports:
        - containerPort: 8686
        volumeMounts:
        - name: emby-config
          mountPath: /config
          subPath: mediaserver/config/lidarr
        - name: emby-config
          mountPath: /downloads
          subPath: mediaserver/download
        - name: emby-config
          mountPath: /incomplete-downloads
          subPath: mediaserver/download
        - name: emby-config
          mountPath: /media
          subPath: mediaserver/media
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: emby-config
        nfs:
          path: /data
          server: 192.168.1.190

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: emby-config
          mountPath: /config
          subPath: mediaserver/config/prowlarr
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: emby-config
        nfs:
          path: /data
          server: 192.168.1.190

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: linuxserver/transmission:latest
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: emby-config
          mountPath: /config
          subPath: mediaserver/config/transmission
        - name: emby-config
          mountPath: /downloads
          subPath: mediaserver/download
        - name: emby-config
          mountPath: /incomplete-downloads
          subPath: mediaserver/download
        - name: emby-config
          mountPath: /media
          subPath: mediaserver/media
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: emby-config
        nfs:
          path: /data
          server: 192.168.1.190

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      containers:
      - name: emby
        image: ghcr.io/linuxserver/emby
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: emby-config
          mountPath: /config
          subPath: mediaserver/config/emby
        - name: emby-config
          mountPath: /media
          subPath: mediaserver/media
        - name: emby-config
          mountPath: /data
          subPath: mediaserver/data
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: emby-config
        nfs:
          path: /data
          server: 192.168.1.190

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: emby-config
          mountPath: /config
          subPath: mediaserver/config/radarr
        - name: emby-config
          mountPath: /movies
          subPath: mediaserver/media/movies
        - name: emby-config
          mountPath: /animation
          subPath: mediaserver/media/animation
        - name: emby-config
          mountPath: /downloads
          subPath: mediaserver/download
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: emby-config
        nfs:
          path: /data
          server: 192.168.1.190

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
      - name: nzbget
        image: linuxserver/nzbget:latest
        ports:
        - containerPort: 6789
        volumeMounts:
        - name: emby-config
          mountPath: /config
          subPath: mediaserver/config/nzbget
        - name: emby-config
          mountPath: /downloads
          subPath: mediaserver/download
        - name: emby-config
          mountPath: /incomplete-downloads
          subPath: mediaserver/download/incomplete
        - name: emby-config
          mountPath: /media
          subPath: mediaserver/media
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: emby-config
        nfs:
          path: /data
          server: 192.168.1.190

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
      - name: bazarr
        image: linuxserver/bazarr:latest
        ports:
        - containerPort: 6767
        volumeMounts:
        - name: emby-config
          mountPath: /config
          subPath: mediaserver/config/bazarr
        - name: emby-config
          mountPath: /media
          subPath: mediaserver/media
        - name: emby-config
          mountPath: /downloads
          subPath: mediaserver/download
        - name: emby-config
          mountPath: /tv
          subPath: mediaserver/media/tv
        - name: emby-config
          mountPath: /movies
          subPath: mediaserver/media/movies
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: emby-config
        nfs:
          path: /data
          server: 192.168.1.190

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
      containers:
      - name: ombi
        image: linuxserver/ombi:latest
        ports:
        - containerPort: 3579
        volumeMounts:
        - name: emby-config
          mountPath: /config
          subPath: mediaserver/config/ombi
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: emby-config
        nfs:
          path: /data
          server: 192.168.1.190
