apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: media-config
          mountPath: /config
        - name: media-storage
          mountPath: /media
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/sonarr
          type: DirectoryOrCreate
      - name: media-storage
        hostPath:
          path: /mnt/sda/data/mediaserver
          type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett:latest
        ports:
        - containerPort: 9117
        volumeMounts:
        - name: media-config
          mountPath: /config
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config
          type: DirectoryOrCreate

---
apiVersion: apps/v1      
kind: Deployment
metadata:
  name: jellyfin
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: docker.io/jellyfin/jellyfin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8096
          protocol: TCP
        volumeMounts:
        - mountPath: /media
          name: media-storage
          readOnly: false
        - mountPath: /config
          name: jellyfin-config
      restartPolicy: Always
      volumes:
      - name: media-storage
        hostPath:
          path: /mnt/sda/data/mediaserver/media
          type: DirectoryOrCreate
      - name: jellyfin-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/jellyfin
          type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisparr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisparr
  template:
    metadata:
      labels:
        app: whisparr
    spec:
      containers:
      - name: whisparr
        image: linuxserver/whisparr:latest
        ports:
        - containerPort: 8192
        volumeMounts:
        - name: media-config
          mountPath: /config
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/whisparr
          type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: linuxserver/lidarr:latest
        ports:
        - containerPort: 8686
        volumeMounts:
        - name: media-config
          mountPath: /config
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/lidarr
          type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: media-config
          mountPath: /config
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/prowlarr
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        ports:
        - containerPort: 6789
        volumeMounts:
        - name: media-config
          mountPath: /config
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
      volumes:
      - name: media-config
        hostPath:
          path: /mnt/sda/data/mediaserver/config/sabnzbd
          type: DirectoryOrCreate