# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-local-pv
  namespace: media-services
spec:
  capacity:
    storage: 1Ti  
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /nmt/sda/data/mediaserver/config 
  persistentVolumeReclaimPolicy: Retain
