# persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage-pvc
  namespace: media-services
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1TiB  # Adjust the storage capacity as needed
  storageClassName: "nfs-storage-media"
  volumeName: media-volume
