# persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-local-pvc
  namespace: media-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti  # Adjust the storage capacity as needed
  storageClassName: "local-path"
  volumeName: media-local-pv
