apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: media-services
spec:
  selector:
    app: jackett
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9117
  type: LoadBalancer
  loadBalancerIP: 192.168.1.212
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media-services
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8989
  type: LoadBalancer
  loadBalancerIP: 192.168.1.213

---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media-services
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8096
  type: LoadBalancer
  loadBalancerIP: 192.168.1.214

---
apiVersion: v1
kind: Service
metadata:
  name: whisparr
  namespace: media-services
spec:
  selector:
    app: whisparr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.1.215

---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media-services
spec:
  selector:
    app: lidarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8686
  type: LoadBalancer
  loadBalancerIP: 192.168.1.216

---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media-services
spec:
  selector:
    app: prowlarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9696
  type: LoadBalancer
  loadBalancerIP: 192.168.1.217
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media-services
spec:
  selector:
    app: sabnzbd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.1.218
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: media-services
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.219
  selector:
    app: transmission
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: emby
  namespace: media-services
spec:
  selector:
    app: emby
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8096
  type: LoadBalancer
  loadBalancerIP: 192.168.1.220
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media-services
spec:
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7878
  type: LoadBalancer
  loadBalancerIP: 192.168.1.221
---
apiVersion: v1
kind: Service
metadata:
  name: nzbget
  namespace: media-services
spec:
  selector:
    app: nzbget
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6789
  type: LoadBalancer
  loadBalancerIP: 192.168.1.222

